### ISSUE TITLE
Error: Frame has been detached.

### ISSUE THREAD

**Issue by alzambranolu13** [ServiceNow/BrowserGym#147]
This time accesing the page ebay.com with instruction "I want to find a silver rolex for man around $13,000 to $15,000 on ebay".
Everything seem to be going well until:
```
INFO:browsergym.experiments.loop:I have filled in the search criteria for a silver Rolex for men with a price range of $13,000 to $15,000. Now, I need to initiate the search to find relevant listings on eBay. The search button is visible and clickable, so I will proceed to click it to see the results.

action:
click('340')

WARNING:browsergym.core.env:An error occured while extracting the dom and axtree. Retrying (4/5 tries left).
MarkingError('Cannot mark a child frame without a bid.')
WARNING:browsergym.experiments.loop:Exception uncaught by agent or environment in task openended.
Error:
Frame has been detached.
Traceback (most recent call last):
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/browsergym/core/env.py", line 481, in _get_obs
    _pre_extract(self.page, self.tags_to_mark)
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/browsergym/core/observation.py", line 73, in _pre_extract
    mark_frames_recursive(page.main_frame, frame_bid="")
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/browsergym/core/observation.py", line 69, in mark_frames_recursive
    raise MarkingError("Cannot mark a child frame without a bid.")
browsergym.core.observation.MarkingError: Cannot mark a child frame without a bid.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/browsergym/experiments/loop.py", line 235, in run
    step_info.from_step(env, action, obs_preprocessor=agent.obs_preprocessor)
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/browsergym/experiments/loop.py", line 353, in from_step
    self.obs, self.reward, self.terminated, self.truncated, env_info = env.step(action)
                                                                       ^^^^^^^^^^^^^^^^
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/gymnasium/wrappers/time_limit.py", line 57, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
                                                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/gymnasium/wrappers/order_enforcing.py", line 56, in step
    return self.env.step(action)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/browsergym/core/env.py", line 389, in step
    obs = self._get_obs()
          ^^^^^^^^^^^^^^^
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/browsergym/core/env.py", line 501, in _get_obs
    _post_extract(self.page)
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/browsergym/core/observation.py", line 102, in _post_extract
    raise e
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/browsergym/core/observation.py", line 87, in _post_extract
    if not frame.frame_element().content_frame() == frame:
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/playwright/sync_api/_generated.py", line 3635, in frame_element
    return mapping.from_impl(self._sync(self._impl_obj.frame_element()))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/playwright/_impl/_sync_base.py", line 109, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/playwright/_impl/_frame.py", line 267, in frame_element
    return from_channel(await self._channel.send("frameElement"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 490, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 99, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.Error: Frame has been detached.
```
Running on Ubuntu 24.04.

**Comment by alzambranolu13** [comment]
Just realized that by just giving instruction "open ebay" I still get the following: 

```
INFO:browsergym.experiments.loop:The previous action was to click the "Google Search" button to search for "eBay". The current page shows the search results for "eBay". To accomplish the goal of opening eBay, I need to click on a link that directs to the eBay website. The link with bid '543' appears to be the main link to eBay's website.

action:
click('543')

WARNING:browsergym.core.observation:Frame marking: not all elements have been visited by the intersection_observer after 1000 ms
WARNING:browsergym.core.observation:Frame marking: not all elements have been visited by the intersection_observer after 1000 ms
WARNING:browsergym.core.observation:Frame marking: not all elements have been visited by the intersection_observer after 1000 ms
WARNING:browsergym.core.observation:Frame marking: not all elements have been visited by the intersection_observer after 1000 ms
WARNING:browsergym.core.observation:Frame marking: not all elements have been visited by the intersection_observer after 1000 ms
WARNING:browsergym.core.observation:Frame marking: not all elements have been visited by the intersection_observer after 1000 ms
WARNING:browsergym.core.observation:Frame marking: not all elements have been visited by the intersection_observer after 1000 ms
WARNING:browsergym.experiments.loop:Exception uncaught by agent or environment in task openended.
Error:
Frame has been detached.
Traceback (most recent call last):
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/browsergym/experiments/loop.py", line 235, in run
    step_info.from_step(env, action, obs_preprocessor=agent.obs_preprocessor)
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/browsergym/experiments/loop.py", line 353, in from_step
    self.obs, self.reward, self.terminated, self.truncated, env_info = env.step(action)
                                                                       ^^^^^^^^^^^^^^^^
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/gymnasium/wrappers/time_limit.py", line 57, in step
    observation, reward, terminated, truncated, info = self.env.step(action)
                                                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/gymnasium/wrappers/order_enforcing.py", line 56, in step
    return self.env.step(action)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/browsergym/core/env.py", line 389, in step
    obs = self._get_obs()
          ^^^^^^^^^^^^^^^
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/browsergym/core/env.py", line 509, in _get_obs
    _post_extract(self.page)
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/browsergym/core/observation.py", line 102, in _post_extract
    raise e
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/browsergym/core/observation.py", line 87, in _post_extract
    if not frame.frame_element().content_frame() == frame:
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/playwright/sync_api/_generated.py", line 3635, in frame_element
    return mapping.from_impl(self._sync(self._impl_obj.frame_element()))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/playwright/_impl/_sync_base.py", line 109, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/playwright/_impl/_frame.py", line 267, in frame_element
    return from_channel(await self._channel.send("frameElement"))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 490, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "/home/alejandra/Documents/AgentLab/agentlab/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 99, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.Error: Frame has been detached.
```

**Comment by gasse** [comment]
There was a bug in the previous fix. Can you try again with the latest version 0.6.4 ?

**Comment by alzambranolu13** [comment]
The new update has worked like a charm! Takes a bit long sometimes but no errors for now :) Thank you Maxime

**Comment by gasse** [comment]
Awesome :)
