### ISSUE TITLE
Error when running WebArena with provided agent

### ISSUE THREAD

**Issue by mingkaid** [ServiceNow/BrowserGym#61]
I was trying to run WebArena with the provided agent code, but ran into the following error saying the `task_id` and `intent_template_id` were left unspecified: 

```
Traceback (most recent call last):
  File "/path/to/BrowserGym/experiments/src/browsergym/experiments/loop.py", line 172, in run
    step_info.from_reset(env, seed=self.env_args.task_seed)
  File "/path/to/BrowserGym/experiments/src/browsergym/experiments/loop.py", line 332, in from_reset
    self.obs, env_info = env.reset(seed=seed)
  File "/path/to/lib/python3.10/site-packages/gymnasium/wrappers/common.py", line 142, in reset
    return super().reset(seed=seed, options=options)
  File "/path/to/lib/python3.10/site-packages/gymnasium/core.py", line 296, in reset
    return self.env.reset(seed=seed, options=options)
  File "/path/to/lib/python3.10/site-packages/gymnasium/wrappers/common.py", line 388, in reset
    return super().reset(seed=seed, options=options)
  File "/path/to/lib/python3.10/site-packages/gymnasium/core.py", line 296, in reset
    return self.env.reset(seed=seed, options=options)
  File "/path/to/BrowserGym/core/src/browsergym/core/env.py", line 166, in reset
    self.task = self.task_entrypoint(seed=seed, **self.task_kwargs)
  File "/path/to/BrowserGym/webarena/src/browsergym/webarena/task.py", line 45, in __init__
    raise ValueError(
ValueError: One and only one of 'task_id' and 'intent_template_id' must be provided (task_id=None, intent_template_id=None).
```

When I ran the sample code in `README.md` there was no issue at all. Below are the versions I used: 

```
browsergym-core==0.3.5.dev0
browsergym-experiments==0.3.5.dev0
browsergym-webarena==0.3.5.dev0
```

Thanks! Let me know if you have any questions.

**Follow-up**: When I manually set the `task_id` in `/BrowserGym/webarena/src/browsergym/webarena/task.py`, it was able to direct me to WebArena tasks (for example, 310 corresponds to question about who made the most contribution under the "AndroidSlidingUpPanel" project on GitLab)

**Comment by gasse** [comment]
Hi @mingkaid , this has been fixed recently in the `main` branch. We will release 0.3.5 soon with this fix included. Meanwhile you can `git pull` from the main branch and `make install`, it should solve your issue.

**Comment by gasse** [comment]
#57

**Comment by gasse** [comment]
Closing this as solved. Please open a new issue if needed.
